// Type declarations for the wasm-bindgen-built JS glue at `../wasm/`.
// The actual file is generated by `wasm-pack build` and lives outside `src/`,
// so we declare its shape here to keep TypeScript happy without expanding
// the package rootDir.

declare module "*/grovedb_proof_view_wasm.js" {
  export default function init(
    moduleOrPath?: string | URL | Request | Response | BufferSource | WebAssembly.Module,
  ): Promise<unknown>;
  export function parseBytes(hexInput: string): unknown;
  export function parseBytesRaw(bytes: Uint8Array): unknown;
  export function parseText(text: string): unknown;
}
